services:
  backend:
    build:
      context: ./be
    ports:
      - "8000:8000"
    container_name: hex-be
    image: hex-backend
    restart: unless-stopped

  frontend:
    build:
      context: ./fe
      args:
        VITE_API_URL: http://localhost:8000
    ports:
      - "3000:80"
    container_name: hex-fe
    image: hex-frontend
    depends_on:
      - backend
    restart: unless-stopped
